-- Knowledge Cell Gitea fork overlay for PostgreSQL 15+.
-- Apply through the fork's migration framework. Do not run this file manually in production.

CREATE TABLE kcp_project (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id bigint NOT NULL,
    name varchar(128) NOT NULL CHECK (btrim(name) <> ''),
    slug varchar(64) NOT NULL CHECK (slug ~ '^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$'),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    created_unix bigint NOT NULL,
    updated_unix bigint NOT NULL,
    UNIQUE (owner_id, slug)
);

CREATE TABLE kcp_repository_group (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES kcp_project(id) ON DELETE CASCADE,
    parent_id bigint NULL,
    name varchar(128) NOT NULL CHECK (btrim(name) <> ''),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    created_unix bigint NOT NULL,
    updated_unix bigint NOT NULL,
    UNIQUE (id, project_id),
    CONSTRAINT kcp_repository_group_parent_fk
        FOREIGN KEY (parent_id, project_id)
        REFERENCES kcp_repository_group(id, project_id)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT kcp_repository_group_not_self_parent CHECK (parent_id IS NULL OR parent_id <> id)
);
CREATE UNIQUE INDEX kcp_repository_group_sibling_name_uq
    ON kcp_repository_group(project_id, parent_id, lower(btrim(name))) NULLS NOT DISTINCT;
CREATE INDEX kcp_repository_group_parent_idx ON kcp_repository_group(project_id, parent_id, id);

CREATE TABLE kcp_repository_group_closure (
    project_id bigint NOT NULL REFERENCES kcp_project(id) ON DELETE CASCADE,
    ancestor_id bigint NOT NULL,
    descendant_id bigint NOT NULL,
    depth integer NOT NULL CHECK (depth >= 0),
    PRIMARY KEY (project_id, ancestor_id, descendant_id),
    FOREIGN KEY (ancestor_id, project_id)
        REFERENCES kcp_repository_group(id, project_id)
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (descendant_id, project_id)
        REFERENCES kcp_repository_group(id, project_id)
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    CHECK ((ancestor_id = descendant_id AND depth = 0) OR (ancestor_id <> descendant_id AND depth > 0))
);
CREATE INDEX kcp_repository_group_closure_descendant_idx
    ON kcp_repository_group_closure(project_id, descendant_id, depth);

CREATE TABLE kcp_repository_placement (
    repository_id bigint PRIMARY KEY REFERENCES repository(id) ON DELETE CASCADE,
    project_id bigint NOT NULL REFERENCES kcp_project(id) ON DELETE CASCADE,
    group_id bigint NULL,
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    created_unix bigint NOT NULL,
    updated_unix bigint NOT NULL,
    FOREIGN KEY (group_id, project_id)
        REFERENCES kcp_repository_group(id, project_id)
        DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX kcp_repository_placement_tree_idx
    ON kcp_repository_placement(project_id, group_id, repository_id);

CREATE TABLE kcp_provider_idempotency (
    operation_id uuid PRIMARY KEY,
    actor_id bigint NOT NULL,
    action varchar(96) NOT NULL,
    resource_digest bytea NOT NULL CHECK (octet_length(resource_digest) = 32),
    request_digest bytea NOT NULL CHECK (octet_length(request_digest) = 32),
    state varchar(16) NOT NULL CHECK (state IN ('PENDING', 'SUCCEEDED', 'FAILED')),
    response_code integer NULL,
    response_body bytea NULL CHECK (response_body IS NULL OR octet_length(response_body) <= 65536),
    external_reference varchar(256) NULL,
    created_unix bigint NOT NULL,
    updated_unix bigint NOT NULL,
    expires_unix bigint NOT NULL
);
CREATE INDEX kcp_provider_idempotency_expiry_idx ON kcp_provider_idempotency(expires_unix);

-- The application transaction must maintain the closure table on create/move and lock the moved
-- root row with SELECT ... FOR UPDATE. A deferred constraint trigger in the full fork will verify
-- that every group has exactly one depth-zero closure row and no cycle before COMMIT.
